# Q6-Concatenate following arrays along axis=0

In [4]:
import numpy as np 

x=np.array([[1,2],[3,4]])
print('First array:') 
print(x) 
print('\n')  

y=np.array([[5,6]]) 
print('Second array:') 
print(y) 
print('\n')  
# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0:') 
print(np.concatenate((x,y),axis=0))  
# you may write or not write axis=0 it will give same output as it takes deafault axis=0 itself

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]]
